server:
  port: 8979

#feign:
#  httpclient:
#    enabled: true

spring:
  application:
    name: order-service
    
eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 3000 #30s->3s  拉取更新服务注册列表


