spring:
  application:
    name: config-server
  profiles:
    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/RapperCL/SpringCloudS
#          search-paths: /spring-config/config-repo
#          username: RapperCL
#          password: best777github

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8099