spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RapperCL/SpringCloudS
          search-paths: configs
          username: RapperCL
          password: best777github
      label: master
#  profiles:
#    active: native
server:
  port: 8888

#spring.application.name=config-server
#server.port=8888
#
#
#spring.cloud.config.server.git.uri=https://github.com/forezp/SpringcloudConfig/
#spring.cloud.config.server.git.searchPaths=respo
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=
#spring.cloud.config.server.git.password=

